### ISSUE TITLE
EdgeGPT support

### ISSUE THREAD

**Issue by getxd-dev** [JasonInd/ChatGPT-DiscordBot#10]
Can you add support for [EdgeGPT](https://github.com/acheong08/EdgeGPT/) (Bing's ChatGPT-4)? Thanks!

**Comment by JasonInd** [comment]
I will update for it to use EdgeGPT for now, I don't have a beta access account. When actual ChatGPT API works again I will look into changing it back. There will be less features as EdgeGPT is new as well.
