### ISSUE TITLE
Bot Typing Effect i.e Stream ChatGPT response in real-time

### ISSUE THREAD

**Issue by otherland** [JasonInd/ChatGPT-DiscordBot#15]
Awesome work! Thank you for creating this. Is there a way to add the Bot Typing Effect i.e Stream ChatGPT response in real-time? I seem to recall revChatGPT had this.

[EDIT]

I guess the bot could send a message each time it detects an end of sentence. Something like:

```
prompt = "What is the most difficult Jimi Hendrix song to play on guitar?"
prev_text = ""
for data in chatbot.ask(
    prompt,
):
    message = data["message"][len(prev_text) :]
    if message and message.endswith(('.','?','!', '."',':')):
	    print(message.strip())
	    prev_text = data["message"]
```

**Comment by JasonInd** [comment]
Can you explain to me what the benefit of streaming is? I know you can do it with revChatGPT, in fact the regular ask function uses streaming anyway and returns the last part. From what I've used in the past the streaming essentially gives you the response character by character, however the end result is the same in terms of what you want in the discord bot that is just the last part of the stream.
