### ISSUE TITLE
Can't find parentid for older chats

### ISSUE THREAD

**Issue by maxilosgundam** [JasonInd/ChatGPT-DiscordBot#3]
How do I extract the parentid if I wanted to resume a previous conversation that is originally created on the website? I'm trying to return to an old chat I had on the site. I can see the conversation id on the link, but I can't seem to find the parentid one.

**Comment by JasonInd** [comment]
You can find parentID from waebsite (I am using firefox) by opening up developer tools (press F12) and then going into debugger.
Open Main Thread -> chat.openai.com -> chat -> (Your conversation ID) . After clicking on your conversation search for the corresponding parentID for your message that you sent by using ctrl+f parentid.
You may need to press ctrl+r in the debugger for it to properly load.

Let me know if you have any problems

**Comment by maxilosgundam** [comment]
Managed to extract the parentid, but it doesn't seem to remember the chat history from that specific chat.
