### ISSUE TITLE
revChatGPT update

### ISSUE THREAD

**Issue by getxd-dev** [JasonInd/ChatGPT-DiscordBot#5]
Hello, I just wanted to let you know that a new [revChatGPT](https://github.com/acheong08/ChatGPT) update has been released and it now utilizes the official ChatGPT API. It now also supports Async and has no ratelimits and it's completely free. It would be cool if you update the bot to that version. Thanks!

**Comment by JasonInd** [comment]
Done, not as many features but updated to use the official API, keep in mind it is only free for the meantime I expect them to fix it on official release of the api.
