### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kWAYTV** [JasonInd/ChatGPT-DiscordBot#7]
Any way to save conversation history right now? i dont see it remembers what i said earlier

**Comment by JasonInd** [comment]
Looking into streaming the questions but right now doesn't look like it works very well I'd ideally like to wait bit more for the API to flesh out a bit more first.

**Comment by kWAYTV** [comment]
Sure thing, if you want to contact, i also made a quite interesting bot kWAY#0001

**Comment by JasonInd** [comment]
Seems to be fixed with updating revchatGPT, if you'd like anything else added please let me know!

**Comment by kWAYTV** [comment]
For multiple user usage, saving the conversations and loading/reading them would be good so they don't mess up / reset a wrong conversation

**Comment by JasonInd** [comment]
Good idea, I can do that however the API looks extremely unstable right now I've seen some people even getting their accounts banned so I will wait till it calms down a little bit again.
